version: '2'
services:
  clickhouse:
    container_name: clickhouse
    image: yandex/clickhouse-server:19.1
    restart: always
    ports:
      - 9000:9000
      - 8123:8123
    volumes:
      - /home/deploy/apps/clickhouse/data:/var/lib/clickhouse
      - /home/deploy/apps/clickhouse/logs:/var/log/clickhouse-server
      - ./config:/etc/clickhouse-server
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
