realt_by_crawl:
  cron: "20 12 * * *"
  class: "CrawlerWorker"
  queue: default
  args:
    parser: 'realt_by'
    threads_count: 1
    proxy_file: '/home/deploy/apps/prices/shared/proxies/proxies2_live.txt'
    verbose: true

nbrb_crawl:
  cron: "30 10 * * *"
  class: "CrawlerWorker"
  queue: default
  args:
    parser: 'nbrb'
    threads_count: 1
    verbose: true