realt_by_crawl:
  cron: "20 12 * * *"
  class: "RealtByWorker"
  queue: default
  args:
    parser: 'realt_by'
    threads_count: 5
    verbose: true

nbrb_crawl:
  cron: "30 10 * * *"
  class: "CrawlerWorker"
  queue: default
  args:
    parser: 'nbrb'
    threads_count: 1
    verbose: true